on:
  push:
    branches: [production]

name: Deploy Slashauth - Demo

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout slashauth-frontend
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Set up Node.js 16
        uses: actions/setup-node@master
        with:
          node-version: '16'

      # this requires a debrief profile to be defined, hence the config lines before make
      - name: Install and deploy to s3
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile debrief
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile debrief
          make deploy-prod
        env:
          AWS_PROFILE: debrief

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          job_name: Slashauth Forms Deployment
          fields: repo,message,commit,author,action,eventName,ref,workflow # selectable (default: repo,message)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
